exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/

# Site title and description
title: "ONS beta web analytics"
description: "Official data on web traffic to hundreds of US federal government websites. Published by the Digital Analytics Program."

# Site's own URL
url: http://analytics-ons-gov-uk.s3-website-eu-west-1.amazonaws.com

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Agencies

# Default data url
data_url: http://analytics-ons-gov-uk.s3-website-eu-west-1.amazonaws.com/ons-data

# GitHub information
org_name: GSA
repo_name: analytics.usa.gov

# twitter information
twitter: usgsa

sass:
  sass_dir: sass
  style: nested
